/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author dangt
 */
public class Bill extends javax.swing.JFrame {

    ReadMoney read = new ReadMoney();
    int timerun = 0;
    float giamGia;
    String textPrice;
    Float price;
    //private Object Tollkit;
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    /**
     * Creates new form OrdersManage
     */
    String ten_ThuNgan;
    String hoa_Don;
    String ten_LoaiNuoc;
    String gia_;
    String so_Luong;
    String ngay_MuaHang;

    /**
     * Creates new form Bill
     */
    public Bill(String maHoaDon, String tenLoaiNuoc, String soLuong, String gia) {
        initComponents();
        this.hoa_Don = maHoaDon;
        this.ten_LoaiNuoc = tenLoaiNuoc;
        this.gia_ = gia;
        this.so_Luong = soLuong;

//        txtThanhTien.setText(price);
        loadData();
        //btnAdd.doClick();
        //chu_chay();
        txtGiamGia.setText("0");
    }

    public void loadData() {
        txtMaHoaDon.setText(hoa_Don);
        txtTenLoaiNuoc.setText(ten_LoaiNuoc);
        txtSoLuong.setText(so_Luong);
        txtGia.setText(gia_);
        //try {
        if (txtGiamGia.getText().equals("100")) {
            giamGia = Float.parseFloat(txtGia.getText()) * Float.parseFloat(txtSoLuong.getText());
        } else {
            if (Float.parseFloat(txtGiamGia.getText()) > 100 || Float.parseFloat(txtGiamGia.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập lại giảm giá (0<= discount >=100)");
            }
            giamGia = Float.parseFloat("0." + txtGiamGia.getText())
                    * Float.parseFloat(txtGia.getText()) * Float.parseFloat(txtSoLuong.getText());
        }
        //Math.round(rate * 10)
        txtThanhGiam.setText(String.valueOf(giamGia));
        price = (Float.parseFloat(gia_) * Float.parseFloat(so_Luong)) - giamGia;
        textPrice = String.valueOf(price);
        // 110000.0  --> length = 8 | 12003450.0  length = 10
        textPrice = textPrice.substring(0, textPrice.length() - 2);
        txtThanhTien.setText(textPrice);
        txtMoney.setText(read.read_money(textPrice) + "VND");
        //} catch (Exception e) {
        //JOptionPane.showMessageDialog(this, "Tạm thời chưa có voucher giảm giá " + txtGiamGia.getText());
        //}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtThanhGiam = new javax.swing.JLabel();
        txtMoney = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jlbPassWord1 = new javax.swing.JLabel();
        jlbPassWord3 = new javax.swing.JLabel();
        jlbPassWord2 = new javax.swing.JLabel();
        jlbPassWord = new javax.swing.JLabel();
        jlbPassWord4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtGia = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtTenLoaiNuoc = new javax.swing.JTextField();
        jlbUserName = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtMaHoaDon = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblChuChay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(126, 87, 194));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Up date");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 130, 30));

        btnAdd1.setBackground(new java.awt.Color(126, 87, 194));
        btnAdd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("Print");
        btnAdd1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 130, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtThanhGiam.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jPanel2.add(txtThanhGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, 30));

        txtMoney.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtMoney.setForeground(new java.awt.Color(255, 0, 0));
        txtMoney.setText("Không nghìn đồng!");
        jPanel2.add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 420, 30));

        txtGiamGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGiamGia.setText("000");
        txtGiamGia.setBorder(null);
        txtGiamGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiamGiaFocusGained(evt);
            }
        });
        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyPressed(evt);
            }
        });
        jPanel2.add(txtGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 30, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel1.setText("% = ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Wifi password: xincamon");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 410, 10));

        jlbPassWord1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord1.setText("Giảm giá");
        jPanel2.add(jlbPassWord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 140, 30));

        jlbPassWord3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord3.setText("Số lượng");
        jPanel2.add(jlbPassWord3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 30));

        jlbPassWord2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord2.setText("Giá");
        jPanel2.add(jlbPassWord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 30));

        jlbPassWord.setBackground(new java.awt.Color(0, 0, 0));
        jlbPassWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord.setText("Tên đơn hàng");
        jPanel2.add(jlbPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 30));

        jlbPassWord4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassWord4.setText("Thành tiền");
        jPanel2.add(jlbPassWord4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 140, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 330, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 10));

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGia.setBorder(null);
        jPanel2.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 130, 10));

        txtTenLoaiNuoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenLoaiNuoc.setBorder(null);
        jPanel2.add(txtTenLoaiNuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 330, 30));

        jlbUserName.setBackground(new java.awt.Color(0, 0, 0));
        jlbUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbUserName.setText("Mã hóa đơn");
        jPanel2.add(jlbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 140, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 10));

        txtMaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaHoaDon.setBorder(null);
        jPanel2.add(txtMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 330, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 330, 10));

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoLuong.setBorder(null);
        jPanel2.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 130, 10));

        lblChuChay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblChuChay.setForeground(new java.awt.Color(51, 153, 0));
        lblChuChay.setText("HÓA ĐƠN");
        jPanel2.add(lblChuChay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 40));

        jLabel5.setText("228 Nguyễn Văn Linh An Khánh Ninh Kiều Cần Thơ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 420, 30));

        txtThanhTien.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jPanel2.add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //System.exit(0);
        //close();
        hoa_Don = txtMaHoaDon.getText();
        ten_LoaiNuoc = txtTenLoaiNuoc.getText();
        so_Luong = txtSoLuong.getText();
        gia_ = txtGia.getText();

        JOptionPane.showMessageDialog(this, "Đã cập nhật lại đơn giá!");
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        JOptionPane.showMessageDialog(this, "Cần kết nối máy in để in đơn hàng!");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void txtGiamGiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiamGiaFocusGained

    }//GEN-LAST:event_txtGiamGiaFocusGained

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        //txtUsername.setBackground(Color.red);
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void txtGiamGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyPressed

    }//GEN-LAST:event_txtGiamGiaKeyPressed
    private Bill() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        toolkit.getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jlbPassWord;
    private javax.swing.JLabel jlbPassWord1;
    private javax.swing.JLabel jlbPassWord2;
    private javax.swing.JLabel jlbPassWord3;
    private javax.swing.JLabel jlbPassWord4;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JLabel lblChuChay;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JLabel txtMoney;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLoaiNuoc;
    private javax.swing.JLabel txtThanhGiam;
    private javax.swing.JLabel txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
